on:
  push:
    branches:
      - main
jobs:
  build:
    if: "!contains(github.event.head_commit.message, 'chore(versionbump)')"
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Conventional Changelog Action
      id: changelog
      uses: TriPSs/conventional-changelog-action@v3
      with:
        git-message: 'chore(versionbump): new version: {version}'
        github-token: ${{ secrets.GITHUB_TOKEN }}
        output-file: 'CHANGELOG.md'
        skip-on-empty: 'true'