name: Push workflow

on:
  push:
    branches: ["gh-release-workflow"]
  pull_request:
    branches: ["gh-release-workflow"]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      GO111MODULE: on
      ACTIONS_ALLOW_UNSECURE_COMMANDS: true
    steps:
      - name: Checkout Source
        uses: actions/checkout@v3
      - name: Unshallow
        run: git fetch --prune --unshallow
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.20.2'

      - name: Create binary
        run: |
          go version 
          go get lnproxy
          go build 
          ls -la 